In [74]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [75]:
data=pd.read_csv('HR_comma_sep.csv')
data

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,Department,salary
0,0.38,0.53,2,157,3,0,1,0,sales,low
1,0.80,0.86,5,262,6,0,1,0,sales,medium
2,0.11,0.88,7,272,4,0,1,0,sales,medium
3,0.72,0.87,5,223,5,0,1,0,sales,low
4,0.37,0.52,2,159,3,0,1,0,sales,low
5,0.41,0.50,2,153,3,0,1,0,sales,low
6,0.10,0.77,6,247,4,0,1,0,sales,low
7,0.92,0.85,5,259,5,0,1,0,sales,low
8,0.89,1.00,5,224,5,0,1,0,sales,low
9,0.42,0.53,2,142,3,0,1,0,sales,low
10,0.45,0.54,2,135,3,0,1,0,sales,low
11,0.11,0.81,6,305,4,0,1,0,sales,low
12,0.84,0.92,4,234,5,0,1,0,sales,low
13,0.41,0.55,2,148,3,0,1,0,sales,low
14,0.36,0.56,2,137,3,0,1,0,sales,low
15,0.38,0.54,2,143,3,0,1,0,sales,low
16,0.45,0.47,2,160,3,0,1,0,sales,low
17,0.78,0.99,4,255,6,0,1,0,sales,low
18,0.45,0.51,2,160,3,1,1,1,sales,low
19,0.76,0.89,5,262,5,0,1,0,sales,low
20,0.11,0.83,6,282,4,0,1,0,sales,low
21,0.38,0.55,2,147,3,0,1,0,sales,low
22,0.09,0.95,6,304,4,0,1,0,sales,low
23,0.46,0.57,2,139,3,0,1,0,sales,low
24,0.40,0.53,2,158,3,0,1,0,sales,low
25,0.89,0.92,5,242,5,0,1,0,sales,low
26,0.82,0.87,4,239,5,0,1,0,sales,low
27,0.40,0.49,2,135,3,0,1,0,sales,low
28,0.41,0.46,2,128,3,0,1,0,accounting,low
29,0.38,0.50,2,132,3,0,1,0,accounting,low
...,...,...,...,...,...,...,...,...,...,...
14969,0.43,0.46,2,157,3,0,1,0,sales,medium
14970,0.78,0.93,4,225,5,0,1,0,sales,medium
14971,0.39,0.45,2,140,3,0,1,0,sales,medium
14972,0.11,0.97,6,310,4,0,1,0,accounting,medium
14973,0.36,0.52,2,143,3,0,1,0,accounting,medium
14974,0.36,0.54,2,153,3,0,1,0,accounting,medium
14975,0.10,0.79,7,310,4,0,1,0,hr,medium
14976,0.40,0.47,2,136,3,0,1,0,hr,medium
14977,0.81,0.85,4,251,6,0,1,0,hr,medium
14978,0.40,0.47,2,144,3,0,1,0,hr,medium
14979,0.09,0.93,6,296,4,0,1,0,technical,medium
14980,0.76,0.89,5,238,5,0,1,0,technical,high
14981,0.73,0.93,5,162,4,0,1,0,technical,low
14982,0.38,0.49,2,137,3,0,1,0,technical,medium
14983,0.72,0.84,5,257,5,0,1,0,technical,medium
14984,0.40,0.56,2,148,3,0,1,0,technical,medium
14985,0.91,0.99,5,254,5,0,1,0,technical,medium
14986,0.85,0.85,4,247,6,0,1,0,technical,low
14987,0.90,0.70,5,206,4,0,1,0,technical,low
14988,0.46,0.55,2,145,3,0,1,0,technical,low
14989,0.43,0.57,2,159,3,1,1,0,technical,low
14990,0.89,0.88,5,228,5,1,1,0,support,low
14991,0.09,0.81,6,257,4,0,1,0,support,low
14992,0.40,0.48,2,155,3,0,1,0,support,low
14993,0.76,0.83,6,293,6,0,1,0,support,low
14994,0.40,0.57,2,151,3,0,1,0,support,low
14995,0.37,0.48,2,160,3,0,1,0,support,low
14996,0.37,0.53,2,143,3,0,1,0,support,low
14997,0.11,0.96,6,280,4,0,1,0,support,low
14998,0.37,0.52,2,158,3,0,1,0,support,low

In [76]:
data.isnull().sum()

satisfaction_level       0
last_evaluation          0
number_project           0
average_montly_hours     0
time_spend_company       0
Work_accident            0
left                     0
promotion_last_5years    0
Department               0
salary                   0
dtype: int64

In [77]:
data.shape

(14999, 10)

In [78]:
df1=data.drop(['Department'],axis='columns')
df1

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,salary
0,0.38,0.53,2,157,3,0,1,0,low
1,0.80,0.86,5,262,6,0,1,0,medium
2,0.11,0.88,7,272,4,0,1,0,medium
3,0.72,0.87,5,223,5,0,1,0,low
4,0.37,0.52,2,159,3,0,1,0,low
5,0.41,0.50,2,153,3,0,1,0,low
6,0.10,0.77,6,247,4,0,1,0,low
7,0.92,0.85,5,259,5,0,1,0,low
8,0.89,1.00,5,224,5,0,1,0,low
9,0.42,0.53,2,142,3,0,1,0,low
10,0.45,0.54,2,135,3,0,1,0,low
11,0.11,0.81,6,305,4,0,1,0,low
12,0.84,0.92,4,234,5,0,1,0,low
13,0.41,0.55,2,148,3,0,1,0,low
14,0.36,0.56,2,137,3,0,1,0,low
15,0.38,0.54,2,143,3,0,1,0,low
16,0.45,0.47,2,160,3,0,1,0,low
17,0.78,0.99,4,255,6,0,1,0,low
18,0.45,0.51,2,160,3,1,1,1,low
19,0.76,0.89,5,262,5,0,1,0,low
20,0.11,0.83,6,282,4,0,1,0,low
21,0.38,0.55,2,147,3,0,1,0,low
22,0.09,0.95,6,304,4,0,1,0,low
23,0.46,0.57,2,139,3,0,1,0,low
24,0.40,0.53,2,158,3,0,1,0,low
25,0.89,0.92,5,242,5,0,1,0,low
26,0.82,0.87,4,239,5,0,1,0,low
27,0.40,0.49,2,135,3,0,1,0,low
28,0.41,0.46,2,128,3,0,1,0,low
29,0.38,0.50,2,132,3,0,1,0,low
...,...,...,...,...,...,...,...,...,...
14969,0.43,0.46,2,157,3,0,1,0,medium
14970,0.78,0.93,4,225,5,0,1,0,medium
14971,0.39,0.45,2,140,3,0,1,0,medium
14972,0.11,0.97,6,310,4,0,1,0,medium
14973,0.36,0.52,2,143,3,0,1,0,medium
14974,0.36,0.54,2,153,3,0,1,0,medium
14975,0.10,0.79,7,310,4,0,1,0,medium
14976,0.40,0.47,2,136,3,0,1,0,medium
14977,0.81,0.85,4,251,6,0,1,0,medium
14978,0.40,0.47,2,144,3,0,1,0,medium
14979,0.09,0.93,6,296,4,0,1,0,medium
14980,0.76,0.89,5,238,5,0,1,0,high
14981,0.73,0.93,5,162,4,0,1,0,low
14982,0.38,0.49,2,137,3,0,1,0,medium
14983,0.72,0.84,5,257,5,0,1,0,medium
14984,0.40,0.56,2,148,3,0,1,0,medium
14985,0.91,0.99,5,254,5,0,1,0,medium
14986,0.85,0.85,4,247,6,0,1,0,low
14987,0.90,0.70,5,206,4,0,1,0,low
14988,0.46,0.55,2,145,3,0,1,0,low
14989,0.43,0.57,2,159,3,1,1,0,low
14990,0.89,0.88,5,228,5,1,1,0,low
14991,0.09,0.81,6,257,4,0,1,0,low
14992,0.40,0.48,2,155,3,0,1,0,low
14993,0.76,0.83,6,293,6,0,1,0,low
14994,0.40,0.57,2,151,3,0,1,0,low
14995,0.37,0.48,2,160,3,0,1,0,low
14996,0.37,0.53,2,143,3,0,1,0,low
14997,0.11,0.96,6,280,4,0,1,0,low
14998,0.37,0.52,2,158,3,0,1,0,low

In [79]:
df2=pd.get_dummies(df1.salary)
df2

       high  low  medium
0         0    1       0
1         0    0       1
2         0    0       1
3         0    1       0
4         0    1       0
5         0    1       0
6         0    1       0
7         0    1       0
8         0    1       0
9         0    1       0
10        0    1       0
11        0    1       0
12        0    1       0
13        0    1       0
14        0    1       0
15        0    1       0
16        0    1       0
17        0    1       0
18        0    1       0
19        0    1       0
20        0    1       0
21        0    1       0
22        0    1       0
23        0    1       0
24        0    1       0
25        0    1       0
26        0    1       0
27        0    1       0
28        0    1       0
29        0    1       0
...     ...  ...     ...
14969     0    0       1
14970     0    0       1
14971     0    0       1
14972     0    0       1
14973     0    0       1
14974     0    0       1
14975     0    0       1
14976     0    0       1
14977     0    0       1
14978     0    0       1
14979     0    0       1
14980     1    0       0
14981     0    1       0
14982     0    0       1
14983     0    0       1
14984     0    0       1
14985     0    0       1
14986     0    1       0
14987     0    1       0
14988     0    1       0
14989     0    1       0
14990     0    1       0
14991     0    1       0
14992     0    1       0
14993     0    1       0
14994     0    1       0
14995     0    1       0
14996     0    1       0
14997     0    1       0
14998     0    1       0

[14999 rows x 3 columns]

In [80]:
merged=pd.concat([df1,df2],axis='columns')
merged

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,salary,high,low,medium
0,0.38,0.53,2,157,3,0,1,0,low,0,1,0
1,0.80,0.86,5,262,6,0,1,0,medium,0,0,1
2,0.11,0.88,7,272,4,0,1,0,medium,0,0,1
3,0.72,0.87,5,223,5,0,1,0,low,0,1,0
4,0.37,0.52,2,159,3,0,1,0,low,0,1,0
5,0.41,0.50,2,153,3,0,1,0,low,0,1,0
6,0.10,0.77,6,247,4,0,1,0,low,0,1,0
7,0.92,0.85,5,259,5,0,1,0,low,0,1,0
8,0.89,1.00,5,224,5,0,1,0,low,0,1,0
9,0.42,0.53,2,142,3,0,1,0,low,0,1,0
10,0.45,0.54,2,135,3,0,1,0,low,0,1,0
11,0.11,0.81,6,305,4,0,1,0,low,0,1,0
12,0.84,0.92,4,234,5,0,1,0,low,0,1,0
13,0.41,0.55,2,148,3,0,1,0,low,0,1,0
14,0.36,0.56,2,137,3,0,1,0,low,0,1,0
15,0.38,0.54,2,143,3,0,1,0,low,0,1,0
16,0.45,0.47,2,160,3,0,1,0,low,0,1,0
17,0.78,0.99,4,255,6,0,1,0,low,0,1,0
18,0.45,0.51,2,160,3,1,1,1,low,0,1,0
19,0.76,0.89,5,262,5,0,1,0,low,0,1,0
20,0.11,0.83,6,282,4,0,1,0,low,0,1,0
21,0.38,0.55,2,147,3,0,1,0,low,0,1,0
22,0.09,0.95,6,304,4,0,1,0,low,0,1,0
23,0.46,0.57,2,139,3,0,1,0,low,0,1,0
24,0.40,0.53,2,158,3,0,1,0,low,0,1,0
25,0.89,0.92,5,242,5,0,1,0,low,0,1,0
26,0.82,0.87,4,239,5,0,1,0,low,0,1,0
27,0.40,0.49,2,135,3,0,1,0,low,0,1,0
28,0.41,0.46,2,128,3,0,1,0,low,0,1,0
29,0.38,0.50,2,132,3,0,1,0,low,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
14969,0.43,0.46,2,157,3,0,1,0,medium,0,0,1
14970,0.78,0.93,4,225,5,0,1,0,medium,0,0,1
14971,0.39,0.45,2,140,3,0,1,0,medium,0,0,1
14972,0.11,0.97,6,310,4,0,1,0,medium,0,0,1
14973,0.36,0.52,2,143,3,0,1,0,medium,0,0,1
14974,0.36,0.54,2,153,3,0,1,0,medium,0,0,1
14975,0.10,0.79,7,310,4,0,1,0,medium,0,0,1
14976,0.40,0.47,2,136,3,0,1,0,medium,0,0,1
14977,0.81,0.85,4,251,6,0,1,0,medium,0,0,1
14978,0.40,0.47,2,144,3,0,1,0,medium,0,0,1
14979,0.09,0.93,6,296,4,0,1,0,medium,0,0,1
14980,0.76,0.89,5,238,5,0,1,0,high,1,0,0
14981,0.73,0.93,5,162,4,0,1,0,low,0,1,0
14982,0.38,0.49,2,137,3,0,1,0,medium,0,0,1
14983,0.72,0.84,5,257,5,0,1,0,medium,0,0,1
14984,0.40,0.56,2,148,3,0,1,0,medium,0,0,1
14985,0.91,0.99,5,254,5,0,1,0,medium,0,0,1
14986,0.85,0.85,4,247,6,0,1,0,low,0,1,0
14987,0.90,0.70,5,206,4,0,1,0,low,0,1,0
14988,0.46,0.55,2,145,3,0,1,0,low,0,1,0
14989,0.43,0.57,2,159,3,1,1,0,low,0,1,0
14990,0.89,0.88,5,228,5,1,1,0,low,0,1,0
14991,0.09,0.81,6,257,4,0,1,0,low,0,1,0
14992,0.40,0.48,2,155,3,0,1,0,low,0,1,0
14993,0.76,0.83,6,293,6,0,1,0,low,0,1,0
14994,0.40,0.57,2,151,3,0,1,0,low,0,1,0
14995,0.37,0.48,2,160,3,0,1,0,low,0,1,0
14996,0.37,0.53,2,143,3,0,1,0,low,0,1,0
14997,0.11,0.96,6,280,4,0,1,0,low,0,1,0
14998,0.37,0.52,2,158,3,0,1,0,low,0,1,0

In [81]:
final=merged.drop(['salary','high'],axis='columns')
final

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,low,medium
0,0.38,0.53,2,157,3,0,1,0,1,0
1,0.80,0.86,5,262,6,0,1,0,0,1
2,0.11,0.88,7,272,4,0,1,0,0,1
3,0.72,0.87,5,223,5,0,1,0,1,0
4,0.37,0.52,2,159,3,0,1,0,1,0
5,0.41,0.50,2,153,3,0,1,0,1,0
6,0.10,0.77,6,247,4,0,1,0,1,0
7,0.92,0.85,5,259,5,0,1,0,1,0
8,0.89,1.00,5,224,5,0,1,0,1,0
9,0.42,0.53,2,142,3,0,1,0,1,0
10,0.45,0.54,2,135,3,0,1,0,1,0
11,0.11,0.81,6,305,4,0,1,0,1,0
12,0.84,0.92,4,234,5,0,1,0,1,0
13,0.41,0.55,2,148,3,0,1,0,1,0
14,0.36,0.56,2,137,3,0,1,0,1,0
15,0.38,0.54,2,143,3,0,1,0,1,0
16,0.45,0.47,2,160,3,0,1,0,1,0
17,0.78,0.99,4,255,6,0,1,0,1,0
18,0.45,0.51,2,160,3,1,1,1,1,0
19,0.76,0.89,5,262,5,0,1,0,1,0
20,0.11,0.83,6,282,4,0,1,0,1,0
21,0.38,0.55,2,147,3,0,1,0,1,0
22,0.09,0.95,6,304,4,0,1,0,1,0
23,0.46,0.57,2,139,3,0,1,0,1,0
24,0.40,0.53,2,158,3,0,1,0,1,0
25,0.89,0.92,5,242,5,0,1,0,1,0
26,0.82,0.87,4,239,5,0,1,0,1,0
27,0.40,0.49,2,135,3,0,1,0,1,0
28,0.41,0.46,2,128,3,0,1,0,1,0
29,0.38,0.50,2,132,3,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...
14969,0.43,0.46,2,157,3,0,1,0,0,1
14970,0.78,0.93,4,225,5,0,1,0,0,1
14971,0.39,0.45,2,140,3,0,1,0,0,1
14972,0.11,0.97,6,310,4,0,1,0,0,1
14973,0.36,0.52,2,143,3,0,1,0,0,1
14974,0.36,0.54,2,153,3,0,1,0,0,1
14975,0.10,0.79,7,310,4,0,1,0,0,1
14976,0.40,0.47,2,136,3,0,1,0,0,1
14977,0.81,0.85,4,251,6,0,1,0,0,1
14978,0.40,0.47,2,144,3,0,1,0,0,1
14979,0.09,0.93,6,296,4,0,1,0,0,1
14980,0.76,0.89,5,238,5,0,1,0,0,0
14981,0.73,0.93,5,162,4,0,1,0,1,0
14982,0.38,0.49,2,137,3,0,1,0,0,1
14983,0.72,0.84,5,257,5,0,1,0,0,1
14984,0.40,0.56,2,148,3,0,1,0,0,1
14985,0.91,0.99,5,254,5,0,1,0,0,1
14986,0.85,0.85,4,247,6,0,1,0,1,0
14987,0.90,0.70,5,206,4,0,1,0,1,0
14988,0.46,0.55,2,145,3,0,1,0,1,0
14989,0.43,0.57,2,159,3,1,1,0,1,0
14990,0.89,0.88,5,228,5,1,1,0,1,0
14991,0.09,0.81,6,257,4,0,1,0,1,0
14992,0.40,0.48,2,155,3,0,1,0,1,0
14993,0.76,0.83,6,293,6,0,1,0,1,0
14994,0.40,0.57,2,151,3,0,1,0,1,0
14995,0.37,0.48,2,160,3,0,1,0,1,0
14996,0.37,0.53,2,143,3,0,1,0,1,0
14997,0.11,0.96,6,280,4,0,1,0,1,0
14998,0.37,0.52,2,158,3,0,1,0,1,0

In [82]:
final.corr()

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,low,medium
satisfaction_level,1.000000,0.105021,-0.142970,-0.020048,-0.100866,0.058697,-0.388375,0.025605,-0.047415,0.031367
last_evaluation,0.105021,1.000000,0.349333,0.339742,0.131591,-0.007104,0.006567,-0.008684,0.005221,0.006191
number_project,-0.142970,0.349333,1.000000,0.417211,0.196786,-0.004741,0.023787,-0.006064,-0.002504,0.007377
average_montly_hours,-0.020048,0.339742,0.417211,1.000000,0.127755,-0.010143,0.071287,-0.003544,-0.001050,0.005007
time_spend_company,-0.100866,0.131591,0.196786,0.127755,1.000000,0.002120,0.144822,0.067433,-0.040110,0.018299
Work_accident,0.058697,-0.007104,-0.004741,-0.010143,0.002120,1.000000,-0.154622,0.039245,-0.006813,0.001856
left,-0.388375,0.006567,0.023787,0.071287,0.144822,-0.154622,1.000000,-0.061788,0.134722,-0.068833
promotion_last_5years,0.025605,-0.008684,-0.006064,-0.003544,0.067433,0.039245,-0.061788,1.000000,-0.082832,0.040985
low,-0.047415,0.005221,-0.002504,-0.001050,-0.040110,-0.006813,0.134722,-0.082832,1.000000,-0.847144
medium,0.031367,0.006191,0.007377,0.005007,0.018299,0.001856,-0.068833,0.040985,-0.847144,1.000000

In [83]:
from sklearn.model_selection import train_test_split

In [84]:
X_train, X_test, y_train, y_test=train_test_split(final[['satisfaction_level','last_evaluation','number_project','average_montly_hours','time_spend_company','Work_accident','promotion_last_5years','low','medium']],final.left,test_size=0.10)

In [85]:
X_test

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,promotion_last_5years,low,medium
12522,0.10,0.95,7,289,4,0,0,1,0
12606,0.38,0.56,2,161,3,0,0,0,1
11469,0.91,0.80,5,169,4,0,0,1,0
11282,0.61,0.42,2,103,8,0,0,0,1
2553,0.51,0.51,4,204,2,0,0,1,0
7893,0.75,0.81,2,247,4,0,0,1,0
14427,0.36,0.48,2,158,3,0,0,1,0
7197,0.53,0.94,4,202,3,1,0,1,0
13752,0.51,0.89,4,233,7,0,0,0,1
3929,0.73,0.62,4,210,4,0,0,0,1
6002,0.79,0.86,3,126,5,0,0,1,0
964,0.38,0.50,2,150,3,1,0,0,1
9505,0.25,0.87,3,265,4,0,0,1,0
2714,0.64,0.55,4,167,3,1,0,0,1
12166,0.43,0.55,2,129,3,0,0,1,0
3130,0.17,0.59,5,250,5,0,0,1,0
410,0.28,0.45,6,218,4,0,0,1,0
3394,0.99,0.60,4,259,4,0,0,1,0
11799,0.72,0.71,4,256,3,0,1,0,1
13475,0.58,0.91,3,154,10,0,0,0,0
9351,0.63,0.59,4,249,2,0,0,1,0
10867,0.80,0.72,4,173,3,0,0,1,0
14774,0.10,0.77,7,291,4,0,0,1,0
10744,0.15,0.81,3,191,5,0,0,0,1
3298,0.50,0.82,3,213,3,0,0,0,0
5216,0.45,0.64,5,133,4,0,0,0,1
14953,0.37,0.45,2,149,3,0,0,1,0
1864,0.37,0.50,2,154,3,0,0,0,1
2203,0.85,0.57,4,216,2,0,0,1,0
8081,0.77,0.52,4,241,3,0,0,0,1
...,...,...,...,...,...,...,...,...,...
4940,0.99,0.71,4,232,3,0,0,0,1
10997,0.51,0.58,4,140,2,1,0,1,0
6078,0.57,0.65,3,163,2,0,0,1,0
10810,0.68,0.76,3,260,4,0,0,1,0
8492,0.26,0.91,6,113,2,0,0,0,1
8119,0.18,0.64,6,154,5,0,0,0,1
10257,0.64,0.96,3,274,3,0,0,1,0
13769,0.72,0.92,3,242,8,0,0,0,1
7129,0.98,0.74,4,202,3,0,0,1,0
6689,0.83,0.94,3,160,3,0,0,1,0
11935,0.50,0.86,3,180,7,0,1,0,0
752,0.37,0.57,2,129,3,0,0,1,0
6735,0.25,0.59,4,166,5,0,0,1,0
1816,0.43,0.50,2,152,3,0,0,0,1
13316,0.37,0.49,3,177,3,0,0,0,0
7591,0.69,0.63,3,137,3,0,0,1,0
6926,0.65,0.62,4,235,3,0,0,1,0
5264,0.93,0.77,5,224,2,0,0,1,0
10188,0.87,0.49,4,213,3,0,0,1,0
10234,0.61,0.74,3,160,3,0,0,0,1
5370,0.64,0.61,3,221,3,0,0,1,0
1724,0.92,0.89,4,241,5,0,0,1,0
7730,0.13,0.72,4,247,3,0,0,0,1
9871,0.53,0.62,4,162,2,0,0,1,0
607,0.11,0.88,5,250,4,0,0,0,1
4504,0.35,0.67,3,119,3,0,1,0,1
13682,0.84,0.66,3,209,2,0,0,1,0
13117,1.00,0.73,5,189,3,1,0,1,0
12409,0.82,0.98,4,233,5,0,0,1,0
5374,0.58,0.62,5,184,3,0,0,1,0

In [87]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [90]:
model.score(X_test,y_test)

0.8046666666666666

In [91]:
model.score(X_train,y_train)

0.784354396621972